routes/web.php
<?php
use Illuminate\Database\Eloquent\Model\Category;
use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\SubcategoryController;
use App\Http\Controllers\Backend\TagController;
use App\Http\Controllers\Backend\ProductController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Backend\UnitController;
use App\Http\Controllers\Backend\AttributeController;
use App\Http\Controllers\Backend\ModuleController;
use App\Http\Controllers\Backend\PermissionController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Backend\RoleController;
use App\Http\Controllers\Backend\CouponController;
use App\Http\Controllers\Backend\SettingController;
use App\Http\Controllers\Frontend\FrontendController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/', [FrontendController::class, 'index'])->name('frontend.index');
Route::get('/category', [FrontendController::class, 'category'])->name('frontend.category');

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::post('/category/getSubcategory', [App\Http\Controllers\Backend\CategoryController::class, 'getSubcategory'])->name('category.getSubcategory');

Route::prefix('backend')->name('backend.')->middleware(['auth'])->group(function(){
    Route::get('/role/assign_form/{id}',[RoleController::class,'assignForm'])->name('role.assign_form');
    Route::post('/role/assign_permission',[RoleController::class,'assignPermission'])->name('role.assign_permission');

    Route::resource('/category', CategoryController::class);
    Route::resource('/tag',TagController::class);
    Route::resource('/subcategory', SubcategoryController::class);
    Route::resource('/product', ProductController::class);
    Route::resource('/unit',UnitController::class);
    Route::resource('/attribute',AttributeController::class);
    Route::resource('/module',ModuleController::class);
    Route::resource('/permission',PermissionController::class);
    Route::resource('/user',UserController::class);
    Route::resource('/role',RoleController::class);
    Route::resource('/coupon',CouponController::class);
    Route::resource('/setting',SettingController::class);

});

app/Models/Unit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Unit extends Model
{
    use HasFactory;
    protected $table = 'units';
    protected $fillable = ['name','status','created_by','updated_by'];
}

app/Http/Controllers/Backend/AttributeController.php
<?php

namespace App\Http\Controllers\backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\AttributeRequest;
use App\Models\Attribute;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AttributeController extends BackendBaseController
{
    protected $panel = "Attribute";
    protected $folder = "backend.attribute.";
    protected $base_route = "backend.attribute.";
    protected $file_path = "";
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['record'] = Attribute::orderby('created_at','desc')->get();
        return view($this->__loadDataToView($this->base_route.'index'),compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view($this->__loadDataToView($this->base_route.'create'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AttributeRequest $request)
    {
        $request->request->add(['created_by' => Auth::user()->id]);
         $record = Attribute::create($request->all());
         if ($record){
             $request->session()->flash('success',$this->panel."Created successfully");
         }else{
             $request->session()->flash('error',$this->panel." creation failed");
         }
         return redirect()->route($this->base_route.'index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['record'] = Attribute::find($id);
        return view($this->__loadDataToView($this->base_route.'show'),compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['record'] = Attribute::find($id);
        if ($data['record']){
            return view($this->__loadDataToView($this->base_route.'index'),compact('data'));
        }else{
            request()->session()->flash('error',$this->panel."Invalid request");
            return redirect()->route($this->base_route.'index');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data['record'] = Attribute::find($id);
        $request->request->add(['updated_by' => Auth::user()->id]);
        if ($data['record']->update($request->all())){
            $request->session()->flash('success',$this->panel."updated successfully");
        }else{
            $request->session()->flash('error',$this->panel." update failed");
        }
        return redirect()->route($this->base_route.'index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,$id)
    {
        $data['record'] = Attribute::find($id);
        if ($data['record']->delete()){
            $request->session()->flash('success',$this->panel.' deletion successfully');
            return redirect()->route($this->base_route.'index');
        }else{
            $request->session()->flash('error',$this->panel.' deletion failed');
            return redirect()->route($this->base_route.'index');
        }
    }
}

app/Http/Controllers/Backend/BackendBaseController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BackendBaseController extends Controller
{
    //function to load data to view file
    protected function __loadDataToView($viewpath){
        view()->composer($viewpath,function ($view){
            $view -> with('panel',$this->panel);
            $view -> with('folder',$this->folder);
            $view -> with('base_route',$this->base_route);
            $view -> with('file_path',$this->file_path);
        });
        return $viewpath;
    }

}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use App\Models\Subcategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CategoryController extends BackendBaseController
{
    protected $panel = 'Category';
    protected $folder = 'backend.category.';
    protected $base_route = 'backend.category.';
    protected $file_path = 'images'. DIRECTORY_SEPARATOR.'backend'.DIRECTORY_SEPARATOR.'category'.DIRECTORY_SEPARATOR;

    function __construct(){
        $this->model = new Category();
        // Using this process is lengthy since we have to use in all controller so we write in web.php..using middleware
        //$this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['records'] = Category::orderby('created_at','desc')->get();
        return view($this->__loadDataToView($this->folder.'index'),compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view($this->__loadDataToView($this->folder.'create'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {

        $request->request->add(['created_by'=>Auth::user()->id]);
        if ($request->hasFile('image_file')){
            $file = $request->file('image_file');
            $file_name = uniqid() . '_' . $file->getClientOriginalName();
            $file->move(public_path() . DIRECTORY_SEPARATOR . $this->file_path , $file_name);
            $request->request->add(['image' => $file_name]);
        }

        $record = $this->model::create($request->all());
        if ($record){
            $request->session()->flash('success',$this->panel.' Created Successfully');
        }else{
            $request->session()->flash('error',$this->panel.' Creation Failed');
        }
        return redirect()->route($this->base_route.'index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['record'] = Category::find($id);
        return view($this->__loadDataToView($this->folder.'show'),compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['record'] = Category::find($id);
        if ($data['record']){
            return view($this->__loadDataToView($this->folder.'edit'),compact('data'));
        }else{
            request()->session()->flash('error','Invalid Request');
            return redirect()->route($this->base_route.'index');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data['record'] = Category::find($id);
        $request->request->add(['updated_by' => Auth::user()->id]);
        if ($request->hasFile('image_file')){
            $file = $request->file('image_file');
            $file_name = uniqid(). '_' . $file->getClientOriginalName();
            $file->move(public_path().DIRECTORY_SEPARATOR.$this->file_path,$file_name);
            $request->request->add(['image' => $file_name]);
            if ($data['record']->image){
                unlink(public_path().DIRECTORY_SEPARATOR. $this->file_path.$data['record']->image);
            }
        }
        if ($data['record']->update($request->all())){
            $request->session()->flash('success', $this->panel. " updated successfully");
        }else{
            $request->session()->flash('error',$this->panel." Update failed");
        }
        return redirect()->route($this->base_route.'index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,$id)
    {
        $data['record'] = Category::find($id);
        if ($data['record'] -> delete()){
            $request->session()->flash('success',$this->panel." delete success");
            return redirect()->route($this->base_route.'index');
        }else{
            $request->session()->flash('error',$this->panel."deletion failed");
            return redirect()->route($this->base_route.'index');
        }
    }
    function getSubcategory(Request $request){
        $subcategoryList = Subcategory::where('category_id',$request->id)->get();

        $option = "<option value=''>Select Subcategory</option>";
        foreach ($subcategoryList as $sub){
            $option .= "<option value='$sub->id'>$sub->name</option>";
        }
        return $option;
    }
}

app/Http/Controllers/Backend/CouponController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\CouponRequest;
use App\Models\Coupon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CouponController extends BackendBaseController
{
    protected $panel = 'Coupon ';
    protected  $folder = 'backend.coupon.';
    protected  $base_route = 'backend.coupon.';
    protected  $file_path = 'images' . DIRECTORY_SEPARATOR . 'backend' . DIRECTORY_SEPARATOR . 'coupon' . DIRECTORY_SEPARATOR;
    public function index()
    {
        $data['records'] = Coupon::orderby('created_at','desc')->get();
        return view($this->__loadDataToView($this->folder . 'index'),compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view($this->__loadDataToView($this->folder . 'create'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CouponRequest $request)
    {
        $request->request->add(['created_by' => Auth::user()->id]);
        $record = Coupon::create($request->all());
        if ($record){
            $request->session()->flash('success',$this->panel. ' created successfully');
        }else{
            $request->session()->flash('error',$this->panel. 'creation failed!!!');
        }
        return redirect()->route($this->base_route.'index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['record'] = Coupon::find($id);
        return view($this->__loadDataToView($this->folder.'show'),compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['record'] = Coupon::find($id);
        if ($data['record']){
            return view($this->__loadDataToView($this->folder.'edit'));
        }else{
            request()->session()->flash('error','Invalid Request');
            return redirect()->route($this->base_route.'index');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CouponRequest $request, $id)
    {
        $data['record'] = Coupon::find($id);
        $request->request->add(['updated_by'=>Auth::user()->id]);

        if ($data['record']->update($request->all())){
            $request->session()->flash('success','Coupon update success');
        }else{
            $request->session()->flash('error','Coupon update failed');
        }
        return redirect()->route($this->base_route . 'index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,$id)
    {
        $data['record'] = Coupon::find($id);
        if ($data['record']->delete()){
            $request->session()->flash('success','Coupon delete success');
            return redirect()->route($this->base_route . 'index');
        }else{
            $request->session()->flash('error','Coupon deletion failed');
            return redirect()->route($this->base_route . 'index');
        }
    }
}

resources/views/backend/unit/create.blade.php
@extends('layouts.backend')
@section('title',$panel,'create')
@section('main-content')
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-8">
                    <div class="card card-primary card-outline">
                        <div class="card-body">
                            {!! Form::open(['route'=>$base_route.'store','method'=>'post']) !!}
                                <div class="form-group">
                                    {!! Form::label('name','Name') !!}
                                    {!! Form::text('name',null,['class'=>'form-control']) !!}
                                </div>
                                <div class="form-group">
                                    {!! Form::label('status','Status') !!}
                                    {!! Form::radio('status',1);!!}Active
                                    {!! Form::radio('status',0);!!}Deactive
                                </div>
                                <div class="form-group">
                                    {!! Form::submit('Save '.$panel,['class'=>'btn btn-info']) !!}
                                    {!! Form::reset('Clear '.$panel,['class'=>'btn btn-warning']) !!}
                                </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/unit/edit.blade.php
@extends('layouts.backend')
@section('title',$panel,'create')
@section('main-content')
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-8">
                    <div class="card card-primary card-outline">
                        <div class="card-body">
                            {!! Form::model($data['record'],['route'=>[$base_route.'update',$data['record']->id],'method'=>'put']) !!}
                            <div class="form-group">
                                {!! Form::label('name','Name') !!}
                                {!! Form::text('name',null,['class'=>'form-control']) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::label('status','Status') !!}
                                {!! Form::radio('status',1);!!}Active
                                {!! Form::radio('status',0);!!}Deactive
                            </div>
                            <div class="form-group">
                                {!! Form::submit('Save '.$panel,['class'=>'btn btn-info']) !!}
                                {!! Form::reset('Clear '.$panel,['class'=>'btn btn-warning']) !!}
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/unit/index.blade.php
@extends('layouts.backend')
@section('title',$panel,'list')
@section('main-content')
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-primary card-outline">
                        <div class="card-body">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>S.N</th>
                                        <th>Name</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                @foreach($data['record'] as $record)
                                    <tbody>
                                    <tr>
                                        <td>{{$loop->index+1}}</td>
                                        <td>{{$record->name}}</td>
                                        <td>
                                            @if($record->status==1)
                                                <span class="text-success">Active</span>
                                            @else
                                                <span class="text-danger">Deactive</span>
                                            @endif
                                        </td>
                                        <td>
                                            <a href="{{route('backend.unit.show',$record->id)}}" class="btn btn-info">View Detail</a>
                                            <a href="{{route('backend.unit.edit',$record->id)}}" class="btn btn-primary">Edit</a>
                                            <form action="{{route('backend.unit.destroy',$record->id)}}" method="post">
                                                <input type="hidden" name="_method" value="DELETE">
                                                @csrf
                                                <button type="submit" class="btn btn-danger">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                    </tbody>
                                @endforeach
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/unit/show.blade.php
@extends('layouts.backend')
@section('title',$panel.' Details')
@section('main-content')
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-primary card-outline">
                        <div class="card-body">
                            <h5 class="card-title">{{$panel}}</h5>
                            @include('backend.common.flash_message')
                            <table class="table-bordered table">
                                <tr>
                                    <th>Name</th>
                                    <td>{{$data['record']->name}}</td>
                                </tr>
                                <tr>
                                    <th>Status</th>
                                    <td>
                                        @if($data['record']->status==1)
                                            <span class="text-success">Active</span>
                                        @else
                                            <span class="text-danger">Deactive</span>
                                        @endif
                                    </td>
                                </tr>
                                <tr>
                                    <th>Created at</th>
                                    <td>{{$data['record']->created_at}}</td>
                                </tr>
                                <tr>
                                    <th>Updated at</th>
                                    <td>{{$data['record']->updated_at}}</td>
                                </tr>
                                <tr>
                                    <th>Created by</th>
                                    <td>{{\App\Models\User::find($data['record']->created_by)->name}}</td>
                                </tr>
                                <tr>
                                    <th>Updated by</th>
                                    <td>
                                        @if($data['record']->updated_by)
                                            {{\App\Models\User::find($data['record']->updated_by)->name}}
                                        @endif
                                    </td>
                                </tr>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection